name: Custom Workflow

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running job 1"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running job 2"
  job3:
    needs: job2
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running job 3" 