name: Ping Google about updated sitemap

on:
  schedule:
    - cron: '0 0 * * *'  # 毎日午前0時に実行
  workflow_dispatch:  # 手動実行も可能

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Google
        run: |
          curl -X GET "https://www.google.com/ping?sitemap=https://www.stellarium.jp/sitemap.xml" 