name: Daily Sitemap Submission

on:
  schedule:
    - cron: '0 3 * * *'  # 毎日午前3時（UTC）に実行。日本時間だと正午頃
  workflow_dispatch:  # 手動実行も可能にしておく

jobs:
  submit-sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install
      
      - name: Generate sitemap
        run: npm run generate-sitemap
      
      - name: Submit sitemap to Google
        run: node scripts/submit-sitemap.js
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_SEARCH_CONSOLE_KEY }}
          SITE_URL: 'stellarium.jp' 